### ISSUE TITLE
Add installation of gitfs dependencies (GitPython)

### ISSUE THREAD

**Issue by johtso** [saltstack-formulas/salt-formula#34]

**Comment by aboe76** [comment]
This is a difficult one because some distributions have GitPython other have pygit2 and some prefer python-dulwich, it depens on which distribution has which python backend packaged.

and you can install the salt-formula's by hand with git. 

If you want you can create a salt.gitfs.sls which will installs the version of choice.
I don't think it should be in the salt.master.sls as a depency.

**Comment by gravyboat** [comment]
@MrMarvin @aboe76 I've discussed the gitpython stuff with s0undt3ch before and he's against including it in the bootstrap as it makes it heavier. A state that handles it would be okay with me though.

**Comment by nmadhok** [comment]
Closing this issue

**Comment by iggy** [comment]
#110 adds modules to install the deps... let me know what distros have packages for dulwich and pygit2 as I didn't have any handy to test installing them.
