### ISSUE TITLE
salt variables are overwritten all over the place

### ISSUE THREAD

**Issue by iggy** [saltstack-formulas/salt-formula#89]
i.e. {% set salt = .... BAD!~!!!

**Comment by aboe76** [comment]
@iggy, please explain further?

**Comment by iggy** [comment]
Apparently I was looking at a rather old clone. My bad.

**Comment by iggy** [comment]
I was actually correct the first time. Just wasn't thinking when I was asked for clarification.

{% from "salt/map.jinja" import salt with context %}

That overwrites the predefined jinja variable "salt", thereby making it impossible to access members of that dict (i.e. salt['grains.get']() fails)

**Comment by nmadhok** [comment]
@iggy Can you please explain further what's happening?

**Comment by iggy** [comment]
Pretty much every file has the following at the top:

{% from "salt/map.jinja" import salt with context %}

That overwrites the main salt jinja variable. So anything you would normally use {{ salt }} for stops working.

i.e. {{ salt['pillar.get']('salt:foo_setting') }} <-- no workie

**Comment by puneetk** [comment]
I think iggy is recommending instead of possibly over writing the global {{ salt }} variable, we use a different variable name in the files. So instead of 
````
{% from "salt/map.jinja" import salt with context %}
````
We use an explicit variable which wont have collisions like 
````
{% from "salt/map.jinja" import salt_settings with context %}
```` 
or 
````
{% from "salt/map.jinja" import salt as salt_settings with context %}
```` 

Among other things, it makes the templates readable and the scope of the settings variable clearer.
